#!/bin/bash

set -euo pipefail

mkdir -p /dev/net
if [ ! -c /dev/net/tun ]; then
  mknod /dev/net/tun c 10 200
fi

set -a
. /etc/easyrsa-vars
set +a

sed \
  -e "s/<LOCAL_IP>/${LOCAL_IP:-0.0.0.0}/" \
  -e "s/<VPN_SUBNET>/${VPN_SUBNET:-10.9.8.0}/" \
  -e "s/<VPN_HOSTNAME>/${VPN_HOSTNAME}/" \
  /etc/openvpn/server.conf.template > /etc/openvpn/server.conf

if [[ -z "$1" ]]
then
  exec openvpn --config /etc/openvpn/server.conf
else
  exec $@
fi
